"""Add importe_neto to FacturaItem

Revision ID: 4156f1aef878
Revises: ba366346df2e
Create Date: 2026-03-01 23:16:24.724443
"""
from alembic import op
import sqlalchemy as sa


revision = '4156f1aef878'
down_revision = 'ba366346df2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura_item', sa.Column('importe_neto', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factura_item', 'importe_neto')
    # ### end Alembic commands ###
