"""drop condicion_iva string column from receptor

Revision ID: 8b58d0aaf80e
Revises: dde3aa11b0df
Create Date: 2026-03-01 19:29:26.711627
"""
from alembic import op
import sqlalchemy as sa


revision = '8b58d0aaf80e'
down_revision = 'dde3aa11b0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receptor', 'condicion_iva')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receptor', sa.Column('condicion_iva', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
