"""add password_changed_at login_attempts locked_until to usuario

Revision ID: 906f4dd4b828
Revises: 1c3f9b2a4d10
Create Date: 2026-03-23 18:11:21.881166
"""
from alembic import op
import sqlalchemy as sa


revision = '906f4dd4b828'
down_revision = '1c3f9b2a4d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=True),
    sa.Column('recurso_id', sa.String(length=36), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_usuario', 'audit_log', ['usuario_id'], unique=False)
    op.add_column('usuario', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'locked_until')
    op.drop_column('usuario', 'login_attempts')
    op.drop_column('usuario', 'password_changed_at')
    op.drop_index('ix_audit_log_usuario', table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
