"""Add items_sin_iva to Factura

Revision ID: ba366346df2e
Revises: 8b58d0aaf80e
Create Date: 2026-03-01 22:43:52.446507
"""
from alembic import op
import sqlalchemy as sa


revision = 'ba366346df2e'
down_revision = '8b58d0aaf80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('items_sin_iva', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factura', 'items_sin_iva')
    # ### end Alembic commands ###
