"""add condicion_iva_id to Receptor

Revision ID: dde3aa11b0df
Revises: 9c1a4d8e72b3
Create Date: 2026-03-01 19:18:42.385272
"""
from alembic import op
import sqlalchemy as sa


revision = 'dde3aa11b0df'
down_revision = '9c1a4d8e72b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('download_artifact_task_id_key', 'download_artifact', type_='unique')
    op.add_column('receptor', sa.Column('condicion_iva_id', sa.Integer(), nullable=True))
    op.alter_column('usuario', 'restringir_dashboard_sensible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'restringir_dashboard_sensible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('receptor', 'condicion_iva_id')
    op.create_unique_constraint('download_artifact_task_id_key', 'download_artifact', ['task_id'])
    # ### end Alembic commands ###
